version: '2'
services:
  serverless-app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: serverless-app
    ports:
      - 3000:3000
    volumes:
      - ./:/serverless
    links:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
