version: '2'
services:
  serverless-app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: serverless-app
    ports:
      - 3000:3000
    volumes:
      - ./app:/serverless/app
