service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource:
    - { "Fn::GetAtt": ["TestDBTable", "Arn" ] }

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  dockerized-serverless-fun1:
    handler: app/index.handler
    events:
    - http:
        method: get
        path: hello

resources:
  Resources:
    TestDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-table
        AttributeDefinitions:
        - AttributeName: propertyA
          AttributeType: S
        KeySchema:
        - AttributeName: propertyA
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
