service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  app:
    handler: app/index.handler
    events:
    - http:
        method: get
        path: hello
